#!/usr/bin/env bash
# Configures nginx to add a custom X-Served-By header with the server's hostname
# shellcheck disable=SC2154
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
if ! grep -q "add_header X-Served-By" /etc/nginx/sites-enabled/default; then
    sed -i "/listen 80 default_server;/a\\ add_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default
fi
service nginx restart
