#!/usr/bin/env bash
# Installs and configures HAProxy to load balance traffic to web-01 and web-02
apt-get update -y
apt-get install -y haproxy

cat >> /etc/haproxy/haproxy.cfg << HAPROXY_CONFIG

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7128-web-01 18.212.54.68:80 check
    server 7128-web-02 3.83.2.51:80 check
HAPROXY_CONFIG

sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

service haproxy restart
