#!/usr/bin/env bash
# Configures nginx with a custom 404 page containing "Ceci n'est pas une page"
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server;/a\\terror_page 404 /404.html;' /etc/nginx/sites-enabled/default
service nginx restart
